#!/bin/bash
# Script pour ajouter la permission d'exécution à tous les sous-répertoires du répertoire courant
# pour l'utilisateur, le groupe et les autres utilisateurs

for item in *; do
  if [ -d "$item" ]; then
    chmod a+x "$item"
  fi
done 
